#ifndef ESP8266NDN_PORT_CHOOSE_HPP
#define ESP8266NDN_PORT_CHOOSE_HPP

#if defined(ARDUINO_ARCH_ESP8266)

#define NDNPH_PORT_CRYPTO_CUSTOM
#define ESP8266NDN_PORT_SHA256_BEARSSL
#define ESP8266NDN_PORT_ECDSA_UECC

#define NDNPH_PORT_QUEUE_SIMPLE

#elif defined(ARDUINO_ARCH_ESP32)

#define NDNPH_PORT_CRYPTO_MBEDTLS

#define NDNPH_PORT_QUEUE_CUSTOM
#define ESP8266NDN_PORT_QUEUE_FREERTOS

#elif defined(ARDUINO_ARCH_NRF52)

#define NDNPH_PORT_CRYPTO_CUSTOM
#define ESP8266NDN_PORT_SHA256_CRYPTOSUITE
#define ESP8266NDN_PORT_ECDSA_UECC

#define NDNPH_PORT_QUEUE_SIMPLE

#else

#error "Unknown ARDUINO_ARCH"

#endif

#endif // ESP8266NDN_PORT_CHOOSE_HPP
