#ifndef ESP8266NDN_PORT_CHOOSE_H
#define ESP8266NDN_PORT_CHOOSE_H

#if defined(ARDUINO_ARCH_ESP8266)

#define NDNPH_PORT_SHA256_CUSTOM
#define ESP8266NDN_PORT_SHA256_BEARSSL

#define NDNPH_PORT_EC_CUSTOM
#define ESP8266NDN_PORT_EC_UECC

#define NDNPH_PORT_QUEUE_SIMPLE

#define NDNPH_PORT_UNIXTIME_SYSTIME
#define NDNPH_PORT_UNIXTIME_SYSTIME_CANSET

#elif defined(ARDUINO_ARCH_ESP32)

#include <sdkconfig.h>

#define NDNPH_HAVE_MBED

#ifdef CONFIG_ESP_SYSTEM_SINGLE_CORE_MODE
#define NDNPH_PORT_QUEUE_SIMPLE
#else
#define NDNPH_PORT_QUEUE_CUSTOM
#define ESP8266NDN_PORT_QUEUE_FREERTOS
#endif // CONFIG_ESP_SYSTEM_SINGLE_CORE_MODE

#define NDNPH_PORT_UNIXTIME_SYSTIME
#define NDNPH_PORT_UNIXTIME_SYSTIME_CANSET

#elif defined(ARDUINO_ARCH_NRF52)

#define NDNPH_PORT_SHA256_CUSTOM
#define ESP8266NDN_PORT_SHA256_CRYPTOSUITE

#define NDNPH_PORT_EC_CUSTOM
#define ESP8266NDN_PORT_EC_UECC

#define NDNPH_PORT_QUEUE_SIMPLE

#elif defined(ARDUINO_ARCH_RP2040)

#define NDNPH_PORT_SHA256_CUSTOM
#define ESP8266NDN_PORT_SHA256_BEARSSL

#define NDNPH_PORT_EC_CUSTOM
#define ESP8266NDN_PORT_EC_UECC

#define NDNPH_PORT_QUEUE_SIMPLE

#else

#error "Unknown ARDUINO_ARCH"

#endif

#endif // ESP8266NDN_PORT_CHOOSE_H
