name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: arduino/setup-arduino-cli@v1.1.1
      - name: install Arduino cores and libraries
        run: |
          arduino-cli version
          arduino-cli core update-index --additional-urls $ARDUINO_CORE_URI
          arduino-cli core install esp8266:esp8266 esp32:esp32 adafruit:nrf52 --additional-urls $ARDUINO_CORE_URI
          arduino-cli lib update-index
          arduino-cli lib install ArduinoUnit
        env:
          ARDUINO_CORE_URI: https://arduino.esp8266.com/stable/package_esp8266com_index.json,https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json,https://www.adafruit.com/package_adafruit_index.json
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install adafruit-nrfutil esptool
      - uses: actions/checkout@v2
      - name: link library
        run: |
          mkdir -p $HOME/Arduino/libraries
          ln -s $GITHUB_WORKSPACE $HOME/Arduino/libraries/esp8266ndn
          git clone --single-branch --depth=1 https://github.com/yoursunny/NDNph.git $HOME/Arduino/libraries/NDNph
      - name: compile in ESP8266
        uses: ./.github/actions/build-examples
        with:
          fqbn: esp8266:esp8266:nodemcuv2
      - name: compile in ESP32
        uses: ./.github/actions/build-examples
        with:
          fqbn: esp32:esp32:esp32wrover
      - name: compile in nRF52
        uses: ./.github/actions/build-examples
        with:
          fqbn: adafruit:nrf52:feather52832
      - name: build docs
        run: |
          sudo apt-get install doxygen
          docs/build.sh
      - name: deploy docs
        uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: cf340d80-1709-45d9-878f-12570d9dcee0
          build-dir: ./docs/html/
        if: ${{ github.event_name == 'push' }}
